ALTER TABLE "Gite" ADD COLUMN "notifNewReservation" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Gite" ADD COLUMN "notifContractSigned" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Gite" ADD COLUMN "notifPrysmNews" BOOLEAN NOT NULL DEFAULT false;
